export const OPEN_MODAL = 'OPEN_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'
export const SET_MODAL_HEADER = 'SET_MODAL_HEADER'

export const FETCHING_LIBRARY = 'FETCHING_LIBRARY'
export const FETCHING_LIBRARY_END = 'FETCHING_LIBRARY_END'

export const ADD_LIBRARY = 'ADD_LIBRARY'
export const SET_LIBRARY = 'SET_LIBRARY'
export const SET_CATEGORY = 'SET_CATEOGORY'
export const SET_FILTERS = 'SET_FILTERS'

export const GET_LOTS = 'GET_LOTS'
export const SET_LOTS = 'SET_LOTS'
export const CLEAR_LOTS = 'CLEAR_LOTS'

export const FETCHING_LOTS = 'FETCHING_LOTS'
export const FETCHING_LOTS_END = 'FETCHING_LOTS_END'

export const SET_PREVIOUS_PAGE = 'SET_PREVIOUS_PAGE'

export const SET_ALL_FILTERS = 'SET_ALL_FILTERS'
export const CLEAR_FILTERS = 'CLEAR_FILTERS'

export const SET_LOT_FILTERS = 'SET_LOT_FILTERS'
export const CLEAR_LOT_FILTERS = 'CLEAR_LOT_FILTERS'
export const REMOVE_LOT_FILTERS = 'REMOVE_LOT_FILTERS'

export const SET_MODAL_PAGE = 'SET_MODAL_PAGE'
export const SET_CATALOG_PAGE = 'SET_CATALOG_PAGE'

export const SET_FILTER_VALUE = 'SET_FILTER_VALUE'

export const SET_OLD_AVAIBLE_FILTERS = 'SET_OLD_AVAIBLE_FILTERS'

export const SET_OLD_FILTERS = 'SET_OLD_FILTERS'

export const SET_SELECTED_FILTERS = 'SET_SELECTED_FILTERS'
export const CLEAR_SELECTED_FILTERS = 'CLEAR_SELECTED_FILTERS'

export const SET_LAST_MODIFED_FILTER = 'SET_LAST_MODIFED_FILTER'

export const SET_ACTIVE_LOT = 'SET_ACTIVE_LOT'
export const CLEAR_ACTIVE_LOT = 'CLEAR_ACTIVE_LOT'

export const SET_PRICE_ORDER = 'SET_PRICE_ORDER'

export const NEED_TO_UPDATE_FILTERS = 'NEED_TO_UPDATE_FILTERS'

export const LOTS_CATEGORY = 155
export const LAYOUT_CATEGORY = 152

export const PLINTH_CATEGORY = 4240
export const HANDLE_CATEGORY = 4670